version: '3.9'

services:
  django:
    build: .
    container_name: realtime
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - pgdb
      - redis
  
  celery:
    build: .
    command:
      - sh
      - -c
      - |
        celery -A realtime_chat worker -l INFO &
        celery -A realtime_chat beat -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
      - redis
  
  pgdb:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
  
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  pgdata: