# Generated by Django 4.2 on 2023-04-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='next_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_transaction_reverse', to='rtc_app.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='prev_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_transaction_reverse', to='rtc_app.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtc_app.coin'),
        ),
    ]
