# Generated by Django 4.2 on 2023-04-26 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtc_app', '0003_alter_transaction_options_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtc_app.groupmodel')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtc_app.chatmodel')),
            ],
        ),
    ]
