# Generated by Django 4.2 on 2023-04-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtc_app', '0004_activeusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
