# Generated by Django 4.2 on 2023-05-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS274bc75lVP83oHXqnPlMrx3fH3ZsUr2T7MQ&usqp=CAU', upload_to=''),
        ),
    ]
